<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>ModernLrc.Tests.Aot</RootNamespace>
    <PublishAot>true</PublishAot>
    <IsPackable>false</IsPackable>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);CS1591;CA1303;IDE0005</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\ModernLrc\ModernLrc.csproj" />
  </ItemGroup>

</Project>
